export default {
        fileNames:['datatables'],
        buildMessage:"",//*Generated File from BuildFile.ts\n*/\n",
        requires:[10],
        buildLocation:"cache/",
        elements:[
            {
                folderName:"DataTables",
                fileNames:[],
                abbr: "dt",
                versions: [
                    ''
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                order:10,
                fileIncludes:{
                    styling:"dataTables"
                },
                position:0        
            },{
                folderName:"SemanticUI",
                fileNames:["semantic"],
                abbr: "se-",
                versions: [
                    '',
                    '2.2.13'
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                fileIncludes:{
                    styling:"semanic",
                    qwerty:'ytrewq'
                },
                order:10 
            },{
                folderName:"SemanticUI",
                fileNames:[],
                abbr: "se",
                versions: [
                    ''
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                fileIncludes:{
                    styling:"semantic"
                },
                order:10 
            },{
                folderName:"Bootstrap-4",
                fileNames:[],
                abbr: "bs4",
                versions: [
                    '',
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                fileIncludes:{
                    styling:"bootstrap4"
                },
                order:10 
            },{
                folderName:"Bootstrap-4",
                fileNames:["bootstrap"],
                abbr: "bs4-",
                versions:[
                    '',
                    '4.1.1',
                    '4.0.0'
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                fileIncludes:{

                },
                order:10 
            },{
                folderName:"Bootstrap",
                fileNames:[],
                abbr: "bs",
                versions: [
                    '',
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                fileIncludes:{
                    styling:"bootstrap"
                },
                order:10 
            },{
                folderName:"Bootstrap",
                fileNames:["bootstrap"],
                abbr:"bs-",
                versions:[
                    '',
                    '3.3.7',
                    '3.3.5',
                    '3.3.6' 
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                fileIncludes:{
                    styling:'bootstrap'
                },
                order:10 
            },{
                folderName:"Foundation",
                fileNames:[],
                abbr: "zf",
                versions: [
                    '',
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                fileIncludes:{
                    
                },
                order:10 
            },{
                folderName:"Foundation",
                fileNames:["foundation"],
                abbr:"zf-",
                versions:[
                    '',
                    '6.4.3',
                    '5.5.2'
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                fileIncludes:{
                    styling:'foundation'
                },
                order:10 
            },{
                folderName:"DataTables",
                fileNames:[
                    "jquery.dataTables",
                    "dataTables.{styling}"
                ],
                abbr: "dt-",
                versions: [
                    '1.10.1',
                    '1.10.2',
                    '1.10.3',
                    '1.10.4',
                    '1.10.5',
                    '1.10.6',
                    '1.10.7',
                    '1.10.8',
                    '1.10.9',
                    '1.10.10',
                    '1.10.11',
                    '1.10.12',
                    '1.10.13',
                    '1.10.14',
                    '1.10.15',
                    '1.10.16',
                    '1.10.17',
                    '1.10.18',
                    '1.10.19',
                    '1.10.20'
                ],
                excludes:[
                    'dt-'
                ],
                fileIncludes:{},
                order:30 
            },{
                folderName:"jQuery",
                fileNames:["jquery-{version}"],
                abbr: "jqc-",
                versions:[
                    '1.12.4',
                    '1.11.3',
                    '1.12.0',
                    '1.12.3',
                ],
                excludes:[
                    "jqc-",
                    'jq-'
                ],
                fileIncludes:{},
                order:20 
            },{
                folderName:"jQuery",
                fileNames:["jquery-{version}"],
                abbr: "jq-",
                versions:[
                    '3.3.1',
                    '2.1.4',
                    '2.2.0',
                    '2.2.3',
                    '3.2.1',
                    '1.12.4'
                ],
                excludes:[
                    "jq-",
                    'jqc-'
                ],
                fileIncludes:{},
                order:20 
            },{
                folderName:"AutoFill",
                fileNames:[
                    'dataTables.autoFill',
                    "autoFill.{styling}"
                    ],
                abbr:"af-",
                versions:[
                    '2.3.3',
                    '2.3.0',
                    '2.2.2',
                    '2.2.1',
                    '2.2.0',
                    '2.1.3',
                    '2.1.2',
                    '2.1.1',
                    '2.1.0',
                    '2.0.0',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.0'
                ],
                excludes:[
                    'af'
                ],
                fileIncludes:{
                    
                },
                order:40 
            },{
                folderName:"Buttons",
                fileNames:[
                    'dataTables.buttons',
                    "buttons.{styling}"
                ],
                abbr:"b-",
                versions:[
                    '1.5.6',
                    '1.5.5',
                    '1.5.2',
                    '1.5.1',
                    '1.5.0',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.1',
                    '1.3.0',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'b-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"ColReorder",
                fileNames:[
                    'dataTables.colReorder',
                    "colReorder.{styling}"
                ],
                abbr:"cr-",
                versions: [
                    '1.5.0',
                    '1.4.1',
                    '1.4.0',
                    '1.3.3',
                    '1.3.2',
                    '1.3.1',
                    '1.3.0',
                    '1.2.0',
                    '1.1.3',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.8',
                    '1.0.7',
                    '1.0.6',
                    '1.0.5',
                    '1.0.4',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ], 
                excludes:[
                    'cr-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"FixedColumns",
                fileNames:[
                    'dataTables.fixedColumns',
                    "fixedColumns.{styling}"
                ],
                abbr:"fc-",
                versions:[
                    '3.2.5',
                    '3.2.4',
                    '3.2.3',
                    '3.2.2',
                    '3.2.1',
                    '3.2.0',
                    '3.1.0',
                    '3.0.4',
                    '3.0.3',
                    '3.0.2',
                    '3.0.1',
                    '3.0.0',
                    '2.0.3',
                    '2.0.1',
                    '2.0.0',
                    '1.1.0',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'fc-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"FixedHeader",
                fileNames:[
                    'dataTables.fixedHeader',
                    "fixedHeader.{styling}"
                ],
                abbr:"fh-",
                versions:[
                    '3.1.4',
                    '3.1.3',
                    '3.1.2',
                    '3.1.1',
                    '3.1.0',
                    '3.0.0',
                    '2.1.2',
                    '2.1.1',
                    '2.1.0',
                    '2.0.6',
                    '2.0.5',
                    '2.0.4',
                    '2.0.3',
                    '2.0.2',
                    '2.0.1',
                    '2.0.0'
                ],
                excludes:[
                    'fh-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"KeyTable",
                fileNames:[
                    'dataTables.keyTable',
                    "keyTable.{styling}"
                ],
                abbr:"kt-",
                versions:[
                    '2.5.0',
                    '2.4.1',
                    '2.4.0',
                    '2.3.2',
                    '2.3.1',
                    '2.3.0',
                    '2.2.1',
                    '2.2.0',
                    '2.1.3',
                    '2.1.2',
                    '2.1.1',
                    '2.1.0',
                    '2.0.0',
                    '1.2.1',
                    '1.2.0',
                    '1.1.7',
                    '1.1.6',
                    '1.1.5',
                    '1.1.4',
                    '1.1.3',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.4',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'kt-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"Responsive",
                fileNames:[
                    'dataTables.responsive',
                    "responsive.{styling}"
                ],
                abbr:"r-",
                versions:[
                    '2.2.2',
                    '2.2.1',
                    '2.2.0',
                    '2.1.1',
                    '2.1.0',
                    '2.0.2',
                    '2.0.1',
                    '2.0.0',
                    '1.0.7',
                    '1.0.6',
                    '1.0.5',
                    '1.0.4',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'r-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"RowGroup",
                fileNames:[
                    'dataTables.rowGroup',
                    "rowGroup.{styling}"
                ],
                abbr:"rg-",
                versions:[
                    '1.1.0',
                    '1.0.4',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'rg-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"RowReorder",
                fileNames:[
                    'dataTables.rowReorder',
                    "rowReorder.{styling}"
                ],
                abbr:"rr-",
                versions:[
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.0'
                ],
                excludes:[
                    'rr-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"Scroller",
                fileNames:[
                    'dataTables.scroller',
                    "scroller.{styling}"
                ],
                abbr:"sc-",
                versions:[
                    '2.0.0',
                    '1.5.0',
                    '1.4.4',
                    '1.4.3',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.0',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.0',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'sc-'
                ],
                fileIncludes:{
                },
                order:40
            },{
                folderName:"Select",
                fileNames:[
                    'dataTables.select',
                    "select.{styling}"
                ],
                abbr:"sl-",
                versions:[
                    '1.3.0',
                    '1.2.6',
                    '1.2.5',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'sl-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"Buttons",
                fileNames:[
                    "buttons.colVis"
                ],
                abbr:"b-colvis-",
                versions:[
                    '1.5.6',
                    '1.5.5',
                    '1.5.2',
                    '1.5.1',
                    '1.5.0',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.1',
                    '1.3.0',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'b-colvis-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"Buttons",
                fileNames:[
                    "buttons.flash"
                ],
                abbr:"b-flash-",
                versions:[
                    '1.5.6',
                    '1.5.5',
                    '1.5.2',
                    '1.5.1',
                    '1.5.0',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.1',
                    '1.3.0',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'b-flash-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"HTML5",
                fileNames:[
                    "buttons.html5"
                ],
                abbr:"b-html5-",
                versions:[
                    '1.5.6',
                    '1.5.5',
                    '1.5.2',
                    '1.5.1',
                    '1.5.0',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.1',
                    '1.3.0',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'b-html5-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"Print",
                fileNames:[
                    "buttons.print"
                ],
                abbr:"b-print-",
                versions:[
                    '1.5.6',
                    '1.5.5',
                    '1.5.2',
                    '1.5.1',
                    '1.5.0',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.1',
                    '1.3.0',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'b-print-'
                ],
                fileIncludes:{},
                order:40
            },{
                folderName:"JSZip",
                fileNames:[
                    "jszip"
                ],
                abbr:"jszip-",
                versions:[
                    '2.5.0',
                    '3.1.3'
                ],
                excludes:[
                    'jszip-'
                ],
                fileIncludes:{},
                order:20
            },{
                folderName:"pdfmake",
                fileNames:[
                    "pdfmake"
                ],
                abbr:"pdfmake-",
                versions:[
                    '0.1.18',
                    '0.1.27',
                    '0.1.32',
                    '0.1.36'
                ],
                excludes:[
                    'pdfmake-'
                ],
                fileIncludes:{},
                order:20
            },{
                folderName:"Moment",
                fileNames:[
                    "moment"
                ],
                abbr:"moment-",
                versions:[
                    '2.18.1'
                ],
                excludes:[
                    'moment-',
                    'momentjs-'
                ],
                fileIncludes:{},
                order:20
            },{
                folderName:"MomentJS",
                fileNames:[
                    "moment"
                ],
                abbr:"momentjs-",
                versions:[
                    '2.10.6',
                    '2.11.2',
                    '2.14.0',
                    '2.18.1'
                ],
                excludes:[
                    'momentjs-',
                    'moment-'
                ],
                fileIncludes:{},
                order:20
            },{
                folderName:"Selectize",
                fileNames:[
                    "selectize"
                ],
                abbr:"selectize-",
                versions:[
                    '0.12.1'
                ],
                excludes:[
                    'selectize-'
                ],
                fileIncludes:{},
                order:20
            },{
                folderName:"Select2",
                fileNames:[
                    "select2"
                ],
                abbr:'select2-',
                versions:[
                    '4.0.0',
                    '4.0.1'
                ],
                excludes:[
                    'select2-'
                ],
                fileIncludes:{},
                order:20
            },{
                folderName:"Quill",
                fileNames:[
                    "quill"
                ],
                //quill.snow for css!!!!
                abbr:'quill-',
                versions:[
                    '0.20.0',
                    '0.20.1',
                    '1.2.4'
                ],
                excludes:[
                    'quill-'
                ],
                fileIncludes:{},
                order:20
            },{
                folderName:"FieldType-Mask",
                fileNames:[
                    "editor.mask"
                ],
                abbr:'mask-',
                versions:[
                    '1.13.4'
                ],
                excludes:[
                    'mask-'
                ],
                fileIncludes:{},
                order:20
            },{
                folderName:"bootstrap-datepicker-4.15.35",
                fileNames:[
                    "bootstrap-datetimepicker"
                ],
                abbr:'date-',
                versions:[
                    '4.15.35'
                ],
                excludes:[
                    'date-'
                ],
                fileIncludes:{},
                order:20
            }
    ]
}