export default {
        filename:['datatables'],
        buildMessage:"",//*Generated File from BuildFile.ts\n*/\n",
        requires:[10],
        elements:[
            {
                folderName:"DataTables",
                fileName:"dataTables",
                abbr: "dt",
                versions: [
                    ''
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                order:10,
                includes:[
                    'jquery.dataTables.js'
                ],
                position:0        
            },{
                folderName:"SemanticUI",
                fileName:"semanticui",
                abbr: "se-",
                versions: [
                    '',
                    '2.2.13'
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                includes:[
                    'semantic.js'
                ],
                order:10 
            },{
                folderName:"SemanticUI",
                fileName:"semanticui",
                abbr: "se",
                versions: [
                    ''
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                includes:[
                    'jquery.dataTables.js',
                    'dataTables.semanticui.js'
                ],
                order:10 
            },{
                folderName:"Bootstrap-4",
                fileName:"bootstrap",
                abbr: "bs4",
                versions: [
                    '',
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                includes:[
                    'jquery.dataTables.js',
                    'dataTables.bootstrap4.js'
                ],
                order:10 
            },{
                folderName:"Bootstrap-4",
                fileName:"bootstrap",
                abbr: "bs4-",
                versions:[
                    '',
                    '4.1.1',
                    '4.0.0'
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                includes:[
                    'bootstrap.js'
                ],
                order:10 
            },{
                folderName:"Bootstrap",
                fileName:"bootstrap",
                abbr: "bs",
                versions: [
                    '',
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                includes:[
                    'jquery.dataTables.js',
                    '*.bootstrap.js'
                ],
                order:10 
            },{
                folderName:"Bootstrap",
                fileName:"bootstrap",
                abbr:"bs-",
                versions:[
                    '',
                    '3.3.7',
                    '3.3.5',
                    '3.3.6' 
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                includes:[
                    'bootstrap.js'
                ],
                order:10 
            },{
                folderName:"Foundation",
                fileName:"foundation",
                abbr: "zf",
                versions: [
                    '',
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                includes:[
                    'jquery.dataTables.js',
                    '*.foundation.*'
                ],
                order:10 
            },{
                folderName:"Foundation",
                fileName:"foundation",
                abbr:"zf-",
                versions:[
                    '',
                    '6.4.3',
                    '5.5.2'
                ],
                excludes:[
                    'dt',
                    'se',
                    'se-',
                    'bs4',
                    'bs4-',
                    'bs',
                    'bs-',
                    'zf',
                    'zf-'
                ],
                includes:[],
                order:10 
            },{
                folderName:"DataTables",
                fileName:"jquery.dataTables",
                abbr: "dt-",
                versions: [
                    '1.10.1',
                    '1.10.2',
                    '1.10.3',
                    '1.10.4',
                    '1.10.5',
                    '1.10.6',
                    '1.10.7',
                    '1.10.8',
                    '1.10.9',
                    '1.10.10',
                    '1.10.11',
                    '1.10.12',
                    '1.10.13',
                    '1.10.14',
                    '1.10.15',
                    '1.10.16',
                    '1.10.17',
                    '1.10.18',
                    '1.10.19',
                    '1.10.20'
                ],
                excludes:[
                    'dt-'
                ],
                includes:[],
                order:30 
            },{
                folderName:"jQuery",
                fileName:"",
                abbr: "jqc-",
                versions:[
                    '1.12.4',
                    '1.11.3',
                    '1.12.0',
                    '1.12.3',
                ],
                excludes:[
                    "jqc-",
                    'jq-'
                ],
                includes:[],
                order:20 
            },{
                folderName:"jQuery",
                fileName:"jquery",
                abbr: "jq-",
                versions:[
                    '3.3.1',
                    '2.1.4',
                    '2.2.0',
                    '2.2.3',
                    '3.2.1',
                    '1.12.4'
                ],
                excludes:[
                    "jq-",
                    'jqc-'
                ],
                includes:[],
                order:20 
            },{
                folderName:"AutoFill",
                fileName:"autoFill",
                abbr:"af-",
                versions:[
                    '2.3.3',
                    '2.3.0',
                    '2.2.2',
                    '2.2.1',
                    '2.2.0',
                    '2.1.3',
                    '2.1.2',
                    '2.1.1',
                    '2.1.0',
                    '2.0.0',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.0'
                ],
                excludes:[
                    'af'
                ],
                includes:[],
                order:40 
            },{
                folderName:"Buttons",
                fileName:"buttons",
                abbr:"b-",
                versions:[
                    '1.5.6',
                    '1.5.5',
                    '1.5.2',
                    '1.5.1',
                    '1.5.0',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.1',
                    '1.3.0',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'b-'
                ],
                includes:[],
                order:40
            },{
                folderName:"ColReorder",
                fileName:"colReorder",
                abbr:"cr-",
                versions: [
                    '1.5.0',
                    '1.4.1',
                    '1.4.0',
                    '1.3.3',
                    '1.3.2',
                    '1.3.1',
                    '1.3.0',
                    '1.2.0',
                    '1.1.3',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.8',
                    '1.0.7',
                    '1.0.6',
                    '1.0.5',
                    '1.0.4',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ], 
                excludes:[
                    'cr-'
                ],
                includes:[],
                order:40
            },{
                folderName:"FixedColumns",
                fileName:"fixedColumns",
                abbr:"fc-",
                versions:[
                    '3.2.5',
                    '3.2.4',
                    '3.2.3',
                    '3.2.2',
                    '3.2.1',
                    '3.2.0',
                    '3.1.0',
                    '3.0.4',
                    '3.0.3',
                    '3.0.2',
                    '3.0.1',
                    '3.0.0',
                    '2.0.3',
                    '2.0.1',
                    '2.0.0',
                    '1.1.0',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'fc-'
                ],
                includes:[],
                order:40
            },{
                folderName:"FixedHeader",
                fileName:"fixedHeader",
                abbr:"fh-",
                versions:[
                    '3.1.4',
                    '3.1.3',
                    '3.1.2',
                    '3.1.1',
                    '3.1.0',
                    '3.0.0',
                    '2.1.2',
                    '2.1.1',
                    '2.1.0',
                    '2.0.6',
                    '2.0.5',
                    '2.0.4',
                    '2.0.3',
                    '2.0.2',
                    '2.0.1',
                    '2.0.0'
                ],
                excludes:[
                    'fh-'
                ],
                includes:[],
                order:40
            },{
                folderName:"KeyTable",
                fileName:"keyTable",
                abbr:"kt-",
                versions:[
                    '2.5.0',
                    '2.4.1',
                    '2.4.0',
                    '2.3.2',
                    '2.3.1',
                    '2.3.0',
                    '2.2.1',
                    '2.2.0',
                    '2.1.3',
                    '2.1.2',
                    '2.1.1',
                    '2.1.0',
                    '2.0.0',
                    '1.2.1',
                    '1.2.0',
                    '1.1.7',
                    '1.1.6',
                    '1.1.5',
                    '1.1.4',
                    '1.1.3',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.4',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'kt-'
                ],
                includes:[],
                order:40
            },{
                folderName:"Responsive",
                fileName:"responsive",
                abbr:"r-",
                versions:[
                    '2.2.2',
                    '2.2.1',
                    '2.2.0',
                    '2.1.1',
                    '2.1.0',
                    '2.0.2',
                    '2.0.1',
                    '2.0.0',
                    '1.0.7',
                    '1.0.6',
                    '1.0.5',
                    '1.0.4',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'r-'
                ],
                includes:[],
                order:40
            },{
                folderName:"RowGroup",
                fileName:"rowGroup",
                abbr:"rg-",
                versions:[
                    '1.1.0',
                    '1.0.4',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'rg-'
                ],
                includes:[],
                order:40
            },{
                folderName:"RowReorder",
                fileName:"rowReorder",
                abbr:"rr-",
                versions:[
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.0'
                ],
                excludes:[
                    'rr-'
                ],
                includes:[],
                order:40
            },{
                folderName:"Scroller",
                fileName:"scroller",
                abbr:"sc-",
                versions:[
                    '2.0.0',
                    '1.5.0',
                    '1.4.4',
                    '1.4.3',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.0',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.0',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'sc-'
                ],
                includes:[],
                order:40
            },{
                folderName:"Select",
                fileName:"select",
                abbr:"sl-",
                versions:[
                    '1.3.0',
                    '1.2.6',
                    '1.2.5',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'sl-'
                ],
                includes:[],
                order:40
            },{
                folderName:"Buttons",
                fileName:"buttons.colVis",
                abbr:"b-colvis-",
                versions:[
                    '1.5.6',
                    '1.5.5',
                    '1.5.2',
                    '1.5.1',
                    '1.5.0',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.1',
                    '1.3.0',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'b-colvis-'
                ],
                includes:[],
                order:40
            },{
                folderName:"Buttons",
                fileName:"buttons.flash",
                abbr:"b-flash-",
                versions:[
                    '1.5.6',
                    '1.5.5',
                    '1.5.2',
                    '1.5.1',
                    '1.5.0',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.1',
                    '1.3.0',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'b-flash-'
                ],
                includes:[],
                order:40
            },{
                folderName:"HTML5",
                fileName:"buttons.html5",
                abbr:"b-html5-",
                versions:[
                    '1.5.6',
                    '1.5.5',
                    '1.5.2',
                    '1.5.1',
                    '1.5.0',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.1',
                    '1.3.0',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'b-html5-'
                ],
                includes:[],
                order:40
            },{
                folderName:"Print",
                fileName:"buttons.print",
                abbr:"b-print-",
                versions:[
                    '1.5.6',
                    '1.5.5',
                    '1.5.2',
                    '1.5.1',
                    '1.5.0',
                    '1.4.2',
                    '1.4.1',
                    '1.4.0',
                    '1.3.1',
                    '1.3.0',
                    '1.2.4',
                    '1.2.3',
                    '1.2.2',
                    '1.2.1',
                    '1.2.0',
                    '1.1.2',
                    '1.1.1',
                    '1.1.0',
                    '1.0.3',
                    '1.0.2',
                    '1.0.1',
                    '1.0.0'
                ],
                excludes:[
                    'b-print-'
                ],
                includes:[],
                order:40
            },{
                folderName:"JSZip",
                fileName:"jszip",
                abbr:"jszip-",
                versions:[
                    '2.5.0',
                    '3.1.3'
                ],
                excludes:[
                    'jszip-'
                ],
                includes:[],
                order:20
            },{
                folderName:"pdfmake",
                fileName:"pdfmake",
                abbr:"pdfmake-",
                versions:[
                    '0.1.18',
                    '0.1.27',
                    '0.1.32',
                    '0.1.36'
                ],
                excludes:[
                    'pdfmake-'
                ],
                includes:[],
                order:20
            },{
                folderName:"Moment",
                fileName:"moment",
                abbr:"moment-",
                versions:[
                    '2.18.1'
                ],
                excludes:[
                    'moment-',
                    'momentjs-'
                ],
                includes:[],
                order:20
            },{
                folderName:"MomentJS",
                fileName:"moment",
                abbr:"momentjs-",
                versions:[
                    '2.10.6',
                    '2.11.2',
                    '2.14.0',
                    '2.18.1'
                ],
                excludes:[
                    'momentjs-',
                    'moment-'
                ],
                includes:[],
                order:20
            },{
                folderName:"Selectize",
                fileName:"selectize",
                abbr:"selectize-",
                versions:[
                    '0.12.1'
                ],
                excludes:[
                    'selectize-'
                ],
                includes:[],
                order:20
            },{
                folderName:"Select2",
                fileName:"select2",
                abbr:'select2-',
                versions:[
                    '4.0.0',
                    '4.0.1'
                ],
                excludes:[
                    'select2-'
                ],
                includes:[],
                order:20
            },{
                folderName:"Quill",
                fileName:"quill",
                //quill.snow for css!!!!
                abbr:'quill-',
                versions:[
                    '0.20.0',
                    '0.20.1',
                    '1.2.4'
                ],
                excludes:[
                    'quill-'
                ],
                includes:[],
                order:20
            },{
                folderName:"FieldType-Mask",
                fileName:"editor.mask",
                abbr:'mask-',
                versions:[
                    '1.13.4'
                ],
                excludes:[
                    'mask-'
                ],
                includes:[],
                order:20
            },{
                folderName:"bootstrap-datepicker-4.15.35",
                fileName:"bootstrap-datetimepicker",
                abbr:'date-',
                versions:[
                    '4.15.35'
                ],
                excludes:[
                    'date-'
                ],
                includes:[],
                order:20
            }
    ]
}